apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: hello-app
 minReadySeconds: 10
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1
 template:
  metadata:
   labels:
    app: hello-app
  spec:
   containers:
    - name: hello-pod
      image: nginx
      ports:
       - containerPort: 80
