apiVersion: v1
kind: Deployment
metadata:
 name: hello-deploy
spec:
 replicas: 10
 selector:
  matchLabels:
   app:hello-deploy
 minReadySeconds: 10
 strategy:
  type: RolloingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1
 template:
  metadata:
   labels:
    app: hello-deploy
  spec:
   containers:
    - name: hello-pod
     image: pradeepkumar2690/dct:signed
     ports:
      - containerPort: 80
   
